### ISSUE TITLE
Can't add labels to a card

### ISSUE THREAD

**Issue by Jannis033** [taskadapter/trello-java-wrapper#27] opened 2018-01-15 15:33 UTC
I can't add a label to a card / I don't know how to do it:

`Card card = new Card();
card.setName(title);
card.addLabels("???"); // <- tried with color, name and id
board.createCard(card);`

**Comment by alexeyOnGitHub** [comment] 2018-04-24 17:34
This is most likely a duplicate of issue #20.

**Closed as completed by alexeyOnGitHub** 2018-04-24 17:34 UTC
